name: Testing a get-charm-paths action

# On pull_request, we:
# * always publish to charmhub at latest/edge/branchname
# * always run tests

on:
  push:

jobs:

  get-charm-paths:
    name: Get the charm paths in this repo
    runs-on: ubuntu-latest
    outputs:
      charm_paths: ${{ steps.get-charm-paths.outputs.charm_paths }}
    steps:
      - name: Try the get-charm-paths action
        id: get-charm-paths
        uses: ca-scribner/github-actions-recipes/get-charm-paths@master

  use-charm-paths:
    name: Use the charm paths to create a matrix
    runs-on: ubuntu-latest
    needs: get-charm-paths
    strategy:
      matrix: 
        charm-path: ${{ fromJson(needs.get-charm-paths.outputs.charm_paths ) }}
    steps:
      - name: Echo charm path
        run: echo "got charm path = ${{ matrix.charm-path }}"
