name: Testing a get-charm-paths action

# On pull_request, we:
# * always publish to charmhub at latest/edge/branchname
# * always run tests

on:
  push:

jobs:

  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Try the get-charm-paths action
        uses: ca-scribner/github-actions-recipes/get-charm-paths@master
