# reusable workflow for checking library versions and opening PRs to bump
name: Update Charm Libraries

on:
  workflow_call:
    inputs:
      charmcraft_channel:
        description: Channel from which to install charmcraft
        default: 'latest/candidate'
        required: false
        type: string
    secrets:
      CHARMCRAFT_CREDENTIALS:
        required: true
  workflow_dispatch:
    inputs:
      charmcraft_channel:
        description: Channel from which to install charmcraft
        default: 'latest/candidate'
        required: false
        type: string

jobs:
  get-charm-paths:
    name: Get paths to all charms in repo
    runs-on: ubuntu-latest
    outputs:
      charm-paths: ${{ steps.get-charm-paths.outputs.charm-paths }}
    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - name: Get paths for all charms in this repo
        id: get-charm-paths
        # TODO: Pin this to a central, released version
        uses: ca-scribner/github-actions-recipes/get-charm-paths-python@master

  update-libs:
    name: Update charm libraries
    runs-on: ubuntu-latest
    needs: get-charm-paths
    strategy:
      fail-fast: false
      matrix:
        charm-path: ${{ fromJson(needs.get-charm-paths.outputs.charm-paths) }}
    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      # - run: sudo snap install charmcraft --channel ${{ inputs.charmcraft_channel }}
      # - name: update charm libs
      #   env:
      #     CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
      #   run: charmcraft fetch-lib
      - name: show charm-2 LIBPATCH before fetch
        run: |
          grep LIBPATCH charms/ca-scribner-test-charm-2/lib/charms/observability_libs/v0/juju_topology.py
      - name: Check libraries
        uses: canonical/charming-actions/check-libraries@1.0.3
        with:
          credentials: "${{ secrets.CHARMCRAFT_CREDENTIALS }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          charm-path: "${{ matrix.charm-path }}"
      - name: show charm-2 LIBPATCH after fetch
        run: |
          grep LIBPATCH charms/ca-scribner-test-charm-2/lib/charms/observability_libs/v0/juju_topology.py
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 5
      - name: Create Pull Request
        id: create-pull-request
        uses: peter-evans/create-pull-request@v4
        with:
          title: 'Update Charm Libs by bot'
          commit-message: Update charm libs
          signoff: false
          delete-branch: true
          branch: automated-update-charm-libs
      - name: Print Created Pull Request
        if: ${{ steps.create-pull-request.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"